# [database]
# db_type = "postgres"
# db_host = "postgres"
# db_port = 5432
# db_database = "postgres"
# db_user = "postgres"
# db_password = "postgres"

# [logs]
# log_level = "info"

[database]
db_type = "mysql"
db_host = "mysql"
db_port = 3306
db_user = "root"
db_password = "mysql"
db_database = "mysql"

[logs]
log_level = "info"
